[README] - New pattern and fixed
betrybe/sd-0x-project-react-testing-library pull request #13
Opened 2020-10-02 15:03 UTC by LizzardMedeiros

2020-10-05 13:59 UTC, mhamaji commented
@LizzardMedeiros , os testes do stryker ainda tão funcionando? Acho que precisava dos template literals para criar as mutações.

2020-10-08 00:12 UTC, albertosca requested changes
Mandou muito bem no README! 🚀

2020-10-08 00:12 UTC, albertosca commented on .eslintrc.json
> +{
Cara, **super crítico** conseguirmos colocar, nos projetos com `.eslint`, as regras do **stylelint!** Dá uma olhada [aqui](https://github.com/stylelint/eslint-config-stylelint) e vê se conseguimos fazer o `.stylelint` agir aqui? Aí podemos pegar os arquivos de config do projeto 13, movie cards library crud, e usar aqui!

Rola?

2020-10-08 00:12 UTC, albertosca commented on README.md
> +### 1. Testando o arquivo App.js
Em todos os requisitos, temos que ter certeza que tudo que o Stryker cobra tá contemplado aqui! Como as configs dele geram as cobranças de forma "automática", vale darmos um double check!

Acho que esse é o maior ponto de atrito que podemos vir a ter com o trabalho!

2020-10-08 00:12 UTC, albertosca commented on README.md
> +    - Deve ser mostrado como opção de filtro, um botão para cada um dos tipos. Além disso, o botão `All` precisa estar sempre visível.
Aqui não rolava de começar com `Teste` também?

2020-10-08 00:12 UTC, albertosca commented on README.md
> +  - O botão de `Próximo pokémon` deverá estar desabilitado quando a lista filtrada de Pokémons tiver apenas um pokémon.
Aqui idem! Não rolava de começar com `Teste` também?

2020-10-08 00:12 UTC, albertosca commented on README.md
> +  - Teste se é msotrado um card com as informações de determinado pokémon.
```suggestion
  - Teste se é mostrado um card com as informações de determinado pokémon.
```

O que seria "mostrar o card" aqui, dado que abaixo cada informação a ser testada é discriminada? 🤔 

Fiquei na dúvida.

2020-10-08 00:12 UTC, albertosca commented on README.md
> +  - Teste se as informações detalhadas do Pokémon selecionado são mostradas na tela.
Idem à questão do card anterior! Dado que abaixo cada informação a ser testada é discriminada, o que esse item contempla?

2020-10-08 00:12 UTC, albertosca commented on README.md
> +Link: [INSERIR LINK]
Lembrar de puxar esse link antes de shipparmos :shipit:!

2020-10-08 00:12 UTC, albertosca commented on README.md
> +O avaliador automático não necessariamente avalia seu projeto na ordem em que os requisitos aparecem no readme. Isso acontece para deixar o processo de avaliação mais rápido. Então, não se assuste se
```suggestion
O avaliador automático não necessariamente avalia seu projeto na ordem em que os requisitos aparecem no README. Isso acontece para deixar o processo de avaliação mais rápido. Então, não se assuste se isso acontecer, ok?
```

2020-10-08 00:14 UTC, albertosca commented
Ah! As versões que o dependabot quer subir, nos PRs que ele abriu, podemos atualizar também! Beleza?

2020-10-09 13:02 UTC, LizzardMedeiros commented on .github/workflows/main.yml
> +          repository-test-name: 'betrybe/sd-0x-block15-project-frontend-online-store-tests'
Done

2020-10-09 13:03 UTC, LizzardMedeiros commented on README.md
> +1. Realizar testes automatizados das suas aplicações em React usando o `Jest` e o `React Testing Library` (RTL)
Done

2020-10-09 13:12 UTC, LizzardMedeiros commented on README.md
> +  - O botão de `Próximo pokémon` deverá estar desabilitado quando a lista filtrada de Pokémons tiver apenas um pokémon.
Pensei nisso, mas lendo novamente o manual da Betina, achei melhor deixar os sub-tópicos dessa forma. Até pra leitura não ficar pedante. Pensei em usar "verifique" também, mas está mais como uma norma do teste do que como teste em si.

2020-10-09 13:16 UTC, LizzardMedeiros commented on README.md
> +  - Teste se é msotrado um card com as informações de determinado pokémon.
Mudarei "mostrado" por "renderizado", acho que fica mais claro. Porei cara informação num subtópico

2020-10-09 13:24 UTC, LizzardMedeiros commented on README.md
> +  - Teste se as informações detalhadas do Pokémon selecionado são mostradas na tela.
Mesmo acima - Done

2020-10-09 13:26 UTC, LizzardMedeiros commented on README.md
> +O avaliador automático não necessariamente avalia seu projeto na ordem em que os requisitos aparecem no readme. Isso acontece para deixar o processo de avaliação mais rápido. Então, não se assuste se
Done

2020-10-09 21:57 UTC, albertosca commented
Dá uma olhadinha nos comentários que tavam _hidden_ depois, @LizzardMedeiros !

2020-10-12 18:38 UTC, LizzardMedeiros commented on .eslintrc.json
> +    "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }],
Estou pedindo ajuda pro pessoal no discord, vou te entregar tudo funcionando na segunda, pode ficar tranquilo

2020-10-12 22:27 UTC, LizzardMedeiros commented on README.md
> +Link: [INSERIR LINK]
Já pinguei!

2020-10-19 15:55 UTC, icaroharry commented on README.md
>    Nesse trabalho o avaliador automatizado **testam os testes de vocês!** A ideia dele é a seguinte: você vai escrever casos de teste para a aplicação, certo? E esses testes têm que garantir que a apl
```suggestion
  Nesse trabalho o avaliador automatizado **testa os testes de vocês!** A ideia dele é a seguinte: você vai escrever casos de teste para a aplicação, certo? E esses testes têm que garantir que a aplicação está funcionando, certo? Pois bem! Se eu quebro uma parte da aplicação, fazendo uma alteração no código, seus testes devem quebrar, certo? Pois é isso que o avaliador faz.
```

2020-10-19 16:38 UTC, merged